version: '3.8'

services:
  flask:
    image: stepaxvii/flask_app:latest
    container_name: ga_flask_app
    ports:
      - "5001:5000"
    env_file:
      - .env
    networks:
      - guestanalytics_backend
      - admin_panel_for_notifications_default
    restart: unless-stopped
    depends_on:
      - postgres_db

  bot:
    image: stepaxvii/bot_app:latest
    container_name: ga_bot_app
    env_file:
      - .env
    networks:
      - guestanalytics_backend
      - admin_panel_for_notifications_default
    restart: unless-stopped
    depends_on:
      - postgres_db

networks:
  guestanalytics_backend:
    driver: bridge
  admin_panel_for_notifications_default:
    external: true