services:
  
  flask:
    image: stepaxvii/flask_app:latest
    container_name: ga_flask_app
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      DB_HOST: admin_panel_for_notifications-postgres-1
      DB_PORT: 5432
    networks:
      - admin_panel_for_notifications_default
    restart: unless-stopped

  bot:
    image: stepaxvii/bot_app:latest
    container_name: ga_bot_app
    env_file:
      - .env
    environment:
      DB_HOST: admin_panel_for_notifications-postgres-1
      DB_PORT: 5432
    networks:
      - admin_panel_for_notifications_default
    restart: unless-stopped

networks:
  admin_panel_for_notifications_default:
    external: true
