version: '3.8'

services:
  flask:
    image: stepaxvii/flask_app:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  bot:
    image: stepaxvii/bot_app:latest
    container_name: bot_app
    env_file:
      - .env
    restart: unless-stopped