version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot_app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер