services:
  postgres:
    image: postgres:13.10-alpine
    container_name: guestanalytics_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT:-5435}:5432"
    volumes:
      - guestanalytics_pgdata:/var/lib/postgresql/data
    networks:
      - guestanalytics_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    image: stepaxvii/flask_app:latest
    container_name: ga_flask_app
    ports:
      - "${FLASK_PORT:-5001}:5000"
    env_file:
      - .env
    networks:
      - guestanalytics_network
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    image: stepaxvii/bot_app:latest
    container_name: ga_bot_app
    env_file:
      - .env
    networks:
      - guestanalytics_network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  guestanalytics_network:
    driver: bridge

volumes:
  guestanalytics_pgdata: