# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY . .

# Открываем порт для Flask
EXPOSE 5000

# Запускаем Flask
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "api.app:app"]