version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h $DB_HOST -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: stepaxvii/flask_app:latest
    container_name: flask_migrations
    env_file:
      - .env
    depends_on:
      - db
    command: alembic upgrade head
    networks:
      - backend

  flask:
    image: stepaxvii/flask_app:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - migrations
    restart: unless-stopped
    networks:
      - backend

  bot:
    image: stepaxvii/bot_app:latest
    container_name: bot_app
    env_file:
      - .env
    depends_on:
      - migrations
    restart: unless-stopped
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
